Task/isc 10 create project models
DShield-ISC/dshield pull request #203
Opened 2022-01-28 19:32 UTC by jdrew-sans

2022-01-28 19:38 UTC, bmyrtil-sans requested changes

2022-01-28 19:38 UTC, bmyrtil-sans commented on srv/isc-agent/plugins/tcp/http/models.py
> +class Signature(Base):
Can we put this in alphabetical order

2022-01-28 19:38 UTC, bmyrtil-sans commented on srv/isc-agent/plugins/tcp/http/models.py
>      sig_id = Column(Integer)
Can we update this to be full name

2022-01-28 19:38 UTC, bmyrtil-sans commented on srv/isc-agent/plugins/tcp/http/models.py
> +        return f"{self.__class__.__name__}({self.id}:{self})"
May we add a space after the colon

2022-01-28 19:38 UTC, bmyrtil-sans commented on srv/isc-agent/plugins/tcp/http/models.py
> +    __tablename__ = 'header_responses'
Shouldnt be plural

2022-01-28 19:38 UTC, bmyrtil-sans commented on srv/isc-agent/plugins/tcp/http/models.py
>      header_field = Column(Text)
Let's remove the `_field` reference. We know its a field. Same for anywhere else using field.

2022-01-28 19:38 UTC, bmyrtil-sans commented on srv/isc-agent/plugins/tcp/http/models.py
> +    #had to change from metadata to data becuase metadata is reserved for the Metadata instance when using a declarative base class.
Got it, you can delete this comment

2022-01-28 19:38 UTC, bmyrtil-sans commented on srv/isc-agent/plugins/tcp/http/models.py
> +    #Will need to be foreign key connecting to request_log_id
Can remove comment

2022-01-28 19:56 UTC, merged

2022-01-29 14:09 UTC, jdrew-sans commented on srv/isc-agent/plugins/tcp/http/models.py
> +class Signature(Base):
Yep